-- PROGRESSION - 1


-- 1. **Create table city**
CREATE TABLE CITY( ID INT NOT NULL PRIMARY KEY, NAME VARCHAR(50) NOT NULL);
-- 2. **Create table referee**
CREATE TABLE REFEREE(ID INT(11) NOT NULL PRIMARY KEY, NAME VARCHAR(50) NOT NULL);
-- 3. **Create table innings**
CREATE TABLE INNINGS(ID INT(11) PRIMARY KEY, INNINGS_NUMBER INT(11) NOT NULL);
-- 4. **Create table extra_type**
CREATE TABLE EXTRA_TYPE(ID INT(11) PRIMARY KEY, NAME VARCHAR(50) NOT NULL);
-- 5. **Create table skill**
CREATE TABLE SKILL(ID INT(11) PRIMARY KEY, NAME VARCHAR(50) NOT NULL);
-- 6. **Create table team**
CREATE TABLE TEAM(ID INT(11) PRIMARY KEY, NAME VARCHAR(50) NOT NULL, COACH VARCHAR(50) NOT NULL, HOME_CITY INT(11) NOT NULL, FOREIGN KEY(HOME_CITY) REFERENCES CITY(ID), CAPTAIN INT(11));
-- 7. **Create table player**
CREATE TABLE PLAYER(ID INT(11) PRIMARY KEY, NAME VARCHAR(50) NOT NULL, COUNTRY VARCHAR(50) NOT NULL, SKILL_ID INT(11) NOT NULL, TEAM_ID INT(11) NOT NULL, FOREIGN KEY(SKILL_ID) REFERENCES SKILL(ID), FOREIGN KEY(TEAM_ID) REFERENCES TEAM(ID));
-- 8. **Create table venue**
CREATE TABLE VENUE(ID INT(11) PRIMARY KEY, STADIUM_NAME VARCHAR(50) NOT NULL, CITY_ID INT(11) NOT NULL, FOREIGN KEY(CITY_ID) REFERENCES CITY(ID));
-- 9. **Create table event**
CREATE TABLE EVENTT(ID INT(11) PRIMARY KEY, INNINGS_ID INT(11) NOT NULL, EVENT_NO INT(11) NOT NULL, RAIDER_ID INT(11) NOT NULL, RAID_POINTS INT(11) NOT NULL, DEFENDING_POINTS INT(11) NOT NULL, CLOCK_IN_SECONDS INT(11) NOT NULL, TEAM_ONE_SCORE INT(11) NOT NULL, TEAM_TWO_SCORE INT(11) NOT NULL, FOREIGN KEY(INNINGS_ID) REFERENCES INNINGS(ID), FOREIGN KEY(RAIDER_ID) REFERENCES PLAYER(ID)); 
-- 10. **Create table extra_event**
CREATE TABLE EXTRA_EVENT(ID INT(11) PRIMARY KEY, NAME VARCHAR(50) NOT NULL);
-- 11. **Create table outcome**
CREATE TABLE OUTCOME(ID INT(11) PRIMARY KEY, STATUS VARCHAR(100) NOT NULL, WINNER_TEAM_ID INT(11), SCORE INT(11), PLAYER_OF_MATCH INT(11), FOREIGN KEY(WINNER_TEAM_ID) REFERENCES TEAM(ID), FOREIGN KEY(PLAYER_OF_MATCH) REFERENCES PLAYER(ID));
-- 12. **Create table game**
CREATE TABLE GAME(ID INT(11) PRIMARY KEY, GAME_DATE DATE NOT NULL, TEAM_ID_1 INT(11) NOT NULL, TEAM_ID_2 INT(11) NOT NULL, VENUE_ID INT(11) NOT NULL, OUTCOME_ID INT(11) NOT NULL, REFEREE_ID_1 INT(11) NOT NULL, REFEREE_ID_2 INT(11) NOT NULL, FIRST_INNINGS_ID INT(11) NOT NULL, SECOND_INNINGS_ID INT(11) NOT NULL, FOREIGN KEY(TEAM_ID_1) REFERENCES TEAM(ID), FOREIGN KEY(TEAM_ID_2) REFERENCES TEAM(ID), FOREIGN KEY(VENUE_ID) REFERENCES VENUE(ID), FOREIGN KEY(OUTCOME_ID) REFERENCES OUTCOME(ID), FOREIGN KEY(REFEREE_ID_1) REFERENCES REFEREE(ID), FOREIGN KEY(REFEREE_ID_2) REFERENCES REFEREE(ID), FOREIGN KEY(FIRST_INNINGS_ID) REFERENCES INNINGS(ID), FOREIGN KEY(SECOND_INNINGS_ID) REFERENCES INNINGS(ID));
-- 13. **Drop table city**
DROP TABLE CITY;
-- 14. **Drop table innings**
DROP TABLE INNINGS;
-- 15. **Drop table skill**
DROP TABLE SKILL;
-- 16. **Drop table extra_type**
DROP TABLE EXTRA_TYPE;